baseURL = "https://packages.rizin.re"
languageCode = "en-us"
title = "Rizin | Package Manager"
theme = "ananke"

ShowBreadCrumbs = true

[params]
  allowExternalUrls = true
  body_classes = "avenir bg-light-gray"
  text_color = "near-black"
  site_logo = "/images/logo.svg"

[menu]
  [[menu.main]]
    identifier = "packages"
    name = "Packages"
    url = "/packages/"
    weight = 10

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
